framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                        default_publish_routing_key: normal
                    queues:
                        messages_normal:
                            binding_keys: [ normal ]

            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                        default_publish_routing_key: high
                    queues:
                        messages_high:
                            binding_keys: [ high ]

            failed: 'doctrine://default?queue_name=failed'
        routing:
            App\Message\AsyncMessageInterface: async
            App\Message\AsyncHighPriorityMessageInterface: async_priority_high
            # sync: 'sync://'
        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_ping_connection
